version: '3.8'
services:
  api:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - my-network
    depends_on:
      - api-db
    env_file:
      - ./.env
    environment:
      - TYPEORM_HOST=api-db
    volumes:
      - api-db-data:/var/lib/postgresql/data

  api-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${API_DB_USER}
      POSTGRES_PASSWORD: ${API_DB_PASSWORD}
      POSTGRES_DB: ${API_DB_NAME}
    ports:
      - 5432:5432
    networks:
      - my-network
    volumes:
      - api-db-data:/var/lib/postgresql/data

   nginx:
    image: nginx
    build:
      context: ./nginx
    restart: always
    ports:
      - 443:443
      - 80:80
      # - 3000:3000
    volumes:
      - cert_volume:/etc/letsencrypt/

networks:
  my-network:
    name: my-network
    driver: bridge

volumes:
  api-db-data:
  cert_volume:
    driver_opts:
      type: none
      o: 'bind'
      device: '${HOME}/certs'